
project_id = "brgycopmuuanrrqmrdmf"

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.dev"]
jwt_expiry = 3600

[functions.create-subscription]
verify_jwt = true

[functions.paystack-webhook]
verify_jwt = false
